//! Mac-only, opt-in, local clipboard history.
//!
//! Fail closed: when the setting is off, callers must not poll or read
//! pasteboard contents. Opt-out wipes the on-disk store.
//!
//! Caps: Free keeps the last 25 items. Pro is treated as unlimited for
//! product copy, but persisted history is hard-capped at 10_000 so an
//! unbounded file cannot grow without limit.

use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::time::{SystemTime, UNIX_EPOCH};

use crate::storekit;

/// Free plan keeps this many most-recent text items.
pub const FREE_CAP: usize = 25;
/// Sane upper bound for Pro. Product says "unlimited"; this is the
/// persistence ceiling so Application Support cannot grow without bound.
pub const PRO_CAP: usize = 10_000;
/// Soft-skip payloads larger than this (bytes of UTF-8). Covers accidental
/// huge "text" copies; images are skipped earlier by type.
pub const MAX_TEXT_BYTES: usize = 512 * 1024;

pub const HISTORY_FILE: &str = "clipboard-history.json";

/// nspasteboard.org markers plus known password-manager / generator UTIs.
/// Comparison is ASCII case-insensitive.
pub const SKIP_UTIS: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "de.petermaurer.TransientPasteboardType",
    "com.typeit4me.clipping",
    "Pasteboard generator type",
    "com.agilebits.onepassword",
    "com.lastpass.sl",
    "net.antelle.keeweb",
    "com.dashlane.secret",
    "com.bitwarden.clipboard",
];

const IMAGE_UTIS: &[&str] = &[
    "public.tiff",
    "public.png",
    "public.jpeg",
    "public.jpeg-2000",
    "public.image",
    "public.heic",
    "public.gif",
    "com.apple.pict",
    "NeXT TIFF v4.0 pasteboard type",
];

const TEXT_UTIS: &[&str] = &[
    "public.utf8-plain-text",
    "public.utf16-plain-text",
    "public.utf16-external-plain-text",
    "public.plain-text",
    "NSStringPboardType",
];

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct HistoryItem {
    pub id: String,
    pub text: String,
    #[serde(rename = "createdAt")]
    pub created_at: i64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
struct HistoryFile {
    #[serde(default)]
    items: Vec<HistoryItem>,
}

#[derive(Debug, Clone, Serialize)]
pub struct HistoryItemView {
    pub id: String,
    pub preview: String,
    #[serde(rename = "textLen")]
    pub text_len: usize,
    #[serde(rename = "createdAt")]
    pub created_at: i64,
}

#[derive(Debug, Clone, Serialize)]
pub struct HistoryList {
    pub enabled: bool,
    pub entitled: bool,
    pub cap: usize,
    pub count: usize,
    pub items: Vec<HistoryItemView>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CaptureDecision {
    Stored,
    Disabled,
    SkippedConfidential,
    SkippedImage,
    SkippedEmpty,
    SkippedHuge,
    Deduped,
}

pub struct Service {
    enabled: Arc<AtomicBool>,
    app_dir: PathBuf,
    inner: Mutex<HistoryFile>,
}

impl Service {
    pub fn new(app_dir: PathBuf, enabled: bool) -> Arc<Self> {
        let loaded = load_file(&app_dir);
        Arc::new(Self {
            enabled: Arc::new(AtomicBool::new(enabled)),
            app_dir,
            inner: Mutex::new(loaded),
        })
    }

    pub fn is_enabled(&self) -> bool {
        self.enabled.load(Ordering::SeqCst)
    }

    /// Opt-out wipes history. Opt-in only flips the flag — the poller primes
    /// `changeCount` without reading contents so the current pasteboard is
    /// not ingested until the next user copy.
    pub fn set_enabled(&self, on: bool) -> Result<(), String> {
        let was = self.enabled.swap(on, Ordering::SeqCst);
        if was && !on {
            self.wipe()?;
        }
        Ok(())
    }

    pub fn wipe(&self) -> Result<(), String> {
        {
            let mut g = self.inner.lock().map_err(|e| e.to_string())?;
            g.items.clear();
        }
        let path = self.app_dir.join(HISTORY_FILE);
        if path.exists() {
            fs::remove_file(&path).map_err(|e| e.to_string())?;
        }
        Ok(())
    }

    pub fn list(&self) -> Result<HistoryList, String> {
        let entitled = storekit::current_entitlement().entitled;
        let cap = cap_for(entitled);
        let enabled = self.is_enabled();
        let mut g = self.inner.lock().map_err(|e| e.to_string())?;
        apply_cap(&mut g.items, cap);
        let items: Vec<HistoryItemView> = g.items.iter().map(item_view).collect();
        Ok(HistoryList {
            enabled,
            entitled,
            cap,
            count: items.len(),
            items,
        })
    }

    pub fn item_text(&self, id: &str) -> Result<String, String> {
        let g = self.inner.lock().map_err(|e| e.to_string())?;
        g.items
            .iter()
            .find(|i| i.id == id)
            .map(|i| i.text.clone())
            .ok_or_else(|| "Clipboard item not found".into())
    }

    /// Record a text snapshot. Callers must already have decided the
    /// pasteboard is safe to read. Still fail-closed if opt-in is off.
    pub fn capture_text(&self, text: &str, types: &[String]) -> Result<CaptureDecision, String> {
        if !self.is_enabled() {
            return Ok(CaptureDecision::Disabled);
        }
        if should_skip_types(types) {
            return Ok(CaptureDecision::SkippedConfidential);
        }
        if should_soft_skip_image(types) {
            return Ok(CaptureDecision::SkippedImage);
        }
        let trimmed = text.trim();
        if trimmed.is_empty() {
            return Ok(CaptureDecision::SkippedEmpty);
        }
        if trimmed.len() > MAX_TEXT_BYTES {
            return Ok(CaptureDecision::SkippedHuge);
        }

        let entitled = storekit::current_entitlement().entitled;
        let cap = cap_for(entitled);
        let mut g = self.inner.lock().map_err(|e| e.to_string())?;
        if g.items
            .first()
            .is_some_and(|i| i.text == trimmed)
        {
            return Ok(CaptureDecision::Deduped);
        }
        g.items.insert(
            0,
            HistoryItem {
                id: next_id(),
                text: trimmed.to_string(),
                created_at: now_secs(),
            },
        );
        apply_cap(&mut g.items, cap);
        persist(&self.app_dir, &g)?;
        Ok(CaptureDecision::Stored)
    }
}

pub fn cap_for(entitled: bool) -> usize {
    if entitled {
        PRO_CAP
    } else {
        FREE_CAP
    }
}

pub fn should_skip_types(types: &[String]) -> bool {
    types.iter().any(|t| is_skip_uti(t))
}

pub fn is_skip_uti(uti: &str) -> bool {
    SKIP_UTIS
        .iter()
        .any(|known| known.eq_ignore_ascii_case(uti.trim()))
}

pub fn has_plain_text_type(types: &[String]) -> bool {
    types.iter().any(|t| {
        TEXT_UTIS
            .iter()
            .any(|known| known.eq_ignore_ascii_case(t.trim()))
    })
}

pub fn should_soft_skip_image(types: &[String]) -> bool {
    if has_plain_text_type(types) {
        return false;
    }
    types.iter().any(|t| {
        IMAGE_UTIS
            .iter()
            .any(|known| known.eq_ignore_ascii_case(t.trim()))
    })
}

fn item_view(item: &HistoryItem) -> HistoryItemView {
    HistoryItemView {
        id: item.id.clone(),
        preview: preview_text(&item.text),
        text_len: item.text.len(),
        created_at: item.created_at,
    }
}

pub fn preview_text(text: &str) -> String {
    let collapsed: String = text.split_whitespace().collect::<Vec<_>>().join(" ");
    const LIMIT: usize = 140;
    if collapsed.chars().count() <= LIMIT {
        collapsed
    } else {
        let mut out: String = collapsed.chars().take(LIMIT).collect();
        out.push('…');
        out
    }
}

fn apply_cap(items: &mut Vec<HistoryItem>, cap: usize) {
    if items.len() > cap {
        items.truncate(cap);
    }
}

fn load_file(app_dir: &PathBuf) -> HistoryFile {
    fs::read_to_string(app_dir.join(HISTORY_FILE))
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default()
}

fn persist(app_dir: &PathBuf, file: &HistoryFile) -> Result<(), String> {
    fs::create_dir_all(app_dir).map_err(|e| e.to_string())?;
    let json = serde_json::to_string_pretty(file).map_err(|e| e.to_string())?;
    fs::write(app_dir.join(HISTORY_FILE), json).map_err(|e| e.to_string())
}

fn next_id() -> String {
    let n = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!("{n:x}")
}

fn now_secs() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    fn tmp() -> PathBuf {
        static N: AtomicU64 = AtomicU64::new(0);
        let dir = std::env::temp_dir().join(format!(
            "mabel-clip-{}-{}",
            std::process::id(),
            N.fetch_add(1, Ordering::Relaxed)
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn types(list: &[&str]) -> Vec<String> {
        list.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn default_off_fails_closed_and_does_not_store() {
        let dir = tmp();
        let svc = Service::new(dir.clone(), false);
        assert!(!svc.is_enabled());
        let decision = svc
            .capture_text("secret", &types(&["public.utf8-plain-text"]))
            .unwrap();
        assert_eq!(decision, CaptureDecision::Disabled);
        assert_eq!(svc.list().unwrap().count, 0);
        assert!(!dir.join(HISTORY_FILE).exists());
    }

    #[test]
    fn concealed_transient_autogenerated_and_password_utis_are_skipped() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        for uti in [
            "org.nspasteboard.ConcealedType",
            "ORG.NSPASTEBOARD.CONCEALEDTYPE",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
            "com.lastpass.sl",
            "de.petermaurer.TransientPasteboardType",
            "com.typeit4me.clipping",
            "Pasteboard generator type",
            "net.antelle.keeweb",
            "com.bitwarden.clipboard",
        ] {
            let decision = svc
                .capture_text("password", &types(&["public.utf8-plain-text", uti]))
                .unwrap();
            assert_eq!(
                decision,
                CaptureDecision::SkippedConfidential,
                "expected skip for {uti}"
            );
        }
        assert_eq!(svc.list().unwrap().count, 0);
    }

    #[test]
    fn image_only_soft_skips_without_storing() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        let decision = svc
            .capture_text("", &types(&["public.png", "public.tiff"]))
            .unwrap();
        assert_eq!(decision, CaptureDecision::SkippedImage);
        assert_eq!(svc.list().unwrap().count, 0);
    }

    #[test]
    fn text_plus_image_keeps_text() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        let decision = svc
            .capture_text(
                "hello",
                &types(&["public.utf8-plain-text", "public.png"]),
            )
            .unwrap();
        assert_eq!(decision, CaptureDecision::Stored);
        assert_eq!(svc.list().unwrap().count, 1);
    }

    #[test]
    fn free_cap_keeps_last_25() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        for i in 0..30 {
            svc.capture_text(&format!("item-{i}"), &types(&["public.utf8-plain-text"]))
                .unwrap();
        }
        let list = svc.list().unwrap();
        assert!(!list.entitled);
        assert_eq!(list.cap, FREE_CAP);
        assert_eq!(list.count, FREE_CAP);
        assert_eq!(list.items[0].preview, "item-29");
        assert_eq!(list.items[24].preview, "item-5");
    }

    #[test]
    fn pro_cap_constant_is_documented_sane_ceiling() {
        assert_eq!(PRO_CAP, 10_000);
        assert!(PRO_CAP > FREE_CAP);
        assert_eq!(cap_for(false), FREE_CAP);
        assert_eq!(cap_for(true), PRO_CAP);
    }

    #[test]
    fn opt_out_wipes_file() {
        let dir = tmp();
        let svc = Service::new(dir.clone(), true);
        svc.capture_text("keep me", &types(&["public.utf8-plain-text"]))
            .unwrap();
        assert!(dir.join(HISTORY_FILE).exists());
        svc.set_enabled(false).unwrap();
        assert!(!svc.is_enabled());
        assert!(!dir.join(HISTORY_FILE).exists());
        assert_eq!(svc.list().unwrap().count, 0);
    }

    #[test]
    fn consecutive_duplicate_is_not_stored_twice() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        let t = types(&["public.utf8-plain-text"]);
        assert_eq!(svc.capture_text("same", &t).unwrap(), CaptureDecision::Stored);
        assert_eq!(svc.capture_text("same", &t).unwrap(), CaptureDecision::Deduped);
        assert_eq!(svc.list().unwrap().count, 1);
    }

    #[test]
    fn huge_text_is_soft_skipped() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        let huge = "x".repeat(MAX_TEXT_BYTES + 1);
        let decision = svc
            .capture_text(&huge, &types(&["public.utf8-plain-text"]))
            .unwrap();
        assert_eq!(decision, CaptureDecision::SkippedHuge);
    }

    #[test]
    fn empty_or_whitespace_is_skipped() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        let t = types(&["public.utf8-plain-text"]);
        assert_eq!(
            svc.capture_text("   \n", &t).unwrap(),
            CaptureDecision::SkippedEmpty
        );
    }

    #[test]
    fn skip_list_covers_nspasteboard_org_conventions() {
        for required in [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
        ] {
            assert!(
                SKIP_UTIS.iter().any(|u| *u == required),
                "missing required skip UTI {required}"
            );
        }
        assert!(should_skip_types(&types(&["org.nspasteboard.ConcealedType"])));
        assert!(!should_skip_types(&types(&["public.utf8-plain-text"])));
    }

    #[test]
    fn preview_collapses_whitespace() {
        assert_eq!(preview_text("hello\n\n  world"), "hello world");
    }

    #[test]
    fn menu_bar_item_and_paste_reuse_are_wired() {
        let ui = include_str!("clipboard_ui.rs");
        assert!(ui.contains("Clipboard History…"));
        let main = include_str!("main.rs");
        assert!(main.contains("mabel_lib::paste::paste_text"));
        assert!(main.contains("clipboard_history_paste"));
        assert!(!main.contains("MabelSpatial"));
    }

    #[test]
    fn version_and_storekit_train_stay_on_1_4_0() {
        let conf = include_str!("../tauri.conf.json");
        assert!(conf.contains("\"version\": \"1.4.0\""));
        let whats = include_str!("../../docs/whatsnew.md");
        assert!(whats.contains("## v1.4.0"));
        assert!(!whats.contains("## v1.5.0"));
    }
}
