//! Mac-only, opt-in, local clipboard history.
//!
//! Enforcer contract (PASS suite b6530197):
//! - Default OFF. Never an always-on clipboard spy.
//! - Local paste history only. Caps are **local slot counts**, never a
//!   cloud quota or sync trigger.
//! - Fail closed when opt-in is off **or** the OS pasteboard is
//!   inaccessible. Do not poll or read contents in either case.
//! - Skip Concealed / Transient / password-manager pasteboard types.
//!   Drop obvious secrets (do not store them).
//! - Not company memory. Coach must not read this store. Distinct from
//!   any future Nexus clipboard toggle — do not merge those settings
//!   without Enforcer. Wipe is a local file delete, never SIEM-logged.
//!
//! Caps: Free keeps the last 25 items. Pro is treated as unlimited for
//! product copy, but persisted history is hard-capped at 10_000 so an
//! unbounded file cannot grow without limit.

use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::time::{SystemTime, UNIX_EPOCH};

use crate::storekit;

/// Free plan keeps this many most-recent text items.
pub const FREE_CAP: usize = 25;
/// Sane upper bound for Pro. Product says "unlimited"; this is the
/// persistence ceiling so Application Support cannot grow without bound.
pub const PRO_CAP: usize = 10_000;
/// Soft-skip payloads larger than this (bytes of UTF-8). Covers accidental
/// huge "text" copies; images are skipped earlier by type.
pub const MAX_TEXT_BYTES: usize = 512 * 1024;

pub const HISTORY_FILE: &str = "clipboard-history.json";

/// nspasteboard.org markers plus known password-manager / generator UTIs.
/// Comparison is ASCII case-insensitive.
pub const SKIP_UTIS: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "de.petermaurer.TransientPasteboardType",
    "com.typeit4me.clipping",
    "Pasteboard generator type",
    "com.agilebits.onepassword",
    "com.lastpass.sl",
    "net.antelle.keeweb",
    "com.dashlane.secret",
    "com.bitwarden.clipboard",
];

const IMAGE_UTIS: &[&str] = &[
    "public.tiff",
    "public.png",
    "public.jpeg",
    "public.jpeg-2000",
    "public.image",
    "public.heic",
    "public.gif",
    "com.apple.pict",
    "NeXT TIFF v4.0 pasteboard type",
];

const TEXT_UTIS: &[&str] = &[
    "public.utf8-plain-text",
    "public.utf16-plain-text",
    "public.utf16-external-plain-text",
    "public.plain-text",
    "NSStringPboardType",
];

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct HistoryItem {
    pub id: String,
    pub text: String,
    #[serde(rename = "createdAt")]
    pub created_at: i64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
struct HistoryFile {
    #[serde(default)]
    items: Vec<HistoryItem>,
}

#[derive(Debug, Clone, Serialize)]
pub struct HistoryItemView {
    pub id: String,
    pub preview: String,
    #[serde(rename = "textLen")]
    pub text_len: usize,
    #[serde(rename = "createdAt")]
    pub created_at: i64,
}

#[derive(Debug, Clone, Serialize)]
pub struct HistoryList {
    pub enabled: bool,
    pub entitled: bool,
    pub cap: usize,
    pub count: usize,
    pub items: Vec<HistoryItemView>,
    /// Always true. Free/Pro limits are local slot counts only.
    #[serde(rename = "localSlotsOnly")]
    pub local_slots_only: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CaptureDecision {
    Stored,
    Disabled,
    SkippedConfidential,
    SkippedImage,
    SkippedEmpty,
    SkippedHuge,
    SkippedSecret,
    DeniedPermission,
    Deduped,
}

pub struct Service {
    enabled: Arc<AtomicBool>,
    app_dir: PathBuf,
    inner: Mutex<HistoryFile>,
    load_error: Mutex<Option<String>>,
}

impl Service {
    pub fn new(app_dir: PathBuf, enabled: bool) -> Arc<Self> {
        let (loaded, error) = match load_file(&app_dir) {
            Ok(file) => (file, None),
            Err(e) => {
                eprintln!("[Mabel] {e}");
                (HistoryFile::default(), Some(e))
            }
        };
        Arc::new(Self {
            enabled: Arc::new(AtomicBool::new(enabled)),
            app_dir,
            inner: Mutex::new(loaded),
            load_error: Mutex::new(error),
        })
    }

    pub fn load_error(&self) -> Option<String> {
        self.load_error.lock().ok().and_then(|g| g.clone())
    }

    pub fn is_enabled(&self) -> bool {
        self.enabled.load(Ordering::SeqCst)
    }

    /// Opt-out wipes history. Opt-in only flips the flag — the poller primes
    /// `changeCount` without reading contents so the current pasteboard is
    /// not ingested until the next user copy.
    pub fn set_enabled(&self, on: bool) -> Result<(), String> {
        let was = self.enabled.swap(on, Ordering::SeqCst);
        if was && !on {
            self.wipe()?;
        }
        Ok(())
    }

    /// Local file delete only. Do not log the wipe, the items, or a
    /// remote event — this is not a Nexus/SIEM action.
    pub fn wipe(&self) -> Result<(), String> {
        {
            let mut g = self.inner.lock().map_err(|e| e.to_string())?;
            g.items.clear();
        }
        let path = self.app_dir.join(HISTORY_FILE);
        if path.exists() {
            fs::remove_file(&path).map_err(|e| e.to_string())?;
        }
        Ok(())
    }

    pub fn list(&self) -> Result<HistoryList, String> {
        if let Some(err) = self.load_error() {
            return Err(err);
        }
        let entitled = storekit::current_entitlement().entitled;
        let cap = cap_for(entitled);
        let enabled = self.is_enabled();
        let mut g = self.inner.lock().map_err(|e| e.to_string())?;
        apply_cap(&mut g.items, cap);
        let items: Vec<HistoryItemView> = g.items.iter().map(item_view).collect();
        Ok(HistoryList {
            enabled,
            entitled,
            cap,
            count: items.len(),
            items,
            local_slots_only: true,
        })
    }

    pub fn item_text(&self, id: &str) -> Result<String, String> {
        let g = self.inner.lock().map_err(|e| e.to_string())?;
        g.items
            .iter()
            .find(|i| i.id == id)
            .map(|i| i.text.clone())
            .ok_or_else(|| "Clipboard item not found".into())
    }

    /// Record a text snapshot. Callers must already have decided the
    /// pasteboard is safe to read. Still fail-closed if opt-in is off.
    pub fn capture_text(&self, text: &str, types: &[String]) -> Result<CaptureDecision, String> {
        self.capture_with_access(text, types, true)
    }

    /// Same as [`Self::capture_text`], with an explicit OS-permission bit.
    /// `os_allowed == false` is fail-closed: nothing is stored or logged.
    pub fn capture_with_access(
        &self,
        text: &str,
        types: &[String],
        os_allowed: bool,
    ) -> Result<CaptureDecision, String> {
        if !self.is_enabled() {
            return Ok(CaptureDecision::Disabled);
        }
        if let Some(err) = self.load_error() {
            return Err(err);
        }
        if !os_allowed {
            return Ok(CaptureDecision::DeniedPermission);
        }
        if should_skip_types(types) {
            return Ok(CaptureDecision::SkippedConfidential);
        }
        if should_soft_skip_image(types) {
            return Ok(CaptureDecision::SkippedImage);
        }
        let trimmed = text.trim();
        if trimmed.is_empty() {
            return Ok(CaptureDecision::SkippedEmpty);
        }
        if trimmed.len() > MAX_TEXT_BYTES {
            return Ok(CaptureDecision::SkippedHuge);
        }
        if looks_like_secret(trimmed) {
            return Ok(CaptureDecision::SkippedSecret);
        }

        let entitled = storekit::current_entitlement().entitled;
        let cap = cap_for(entitled);
        let mut g = self.inner.lock().map_err(|e| e.to_string())?;
        if g.items
            .first()
            .is_some_and(|i| i.text == trimmed)
        {
            return Ok(CaptureDecision::Deduped);
        }
        g.items.insert(
            0,
            HistoryItem {
                id: next_id(),
                text: trimmed.to_string(),
                created_at: now_secs(),
            },
        );
        apply_cap(&mut g.items, cap);
        persist(&self.app_dir, &g)?;
        Ok(CaptureDecision::Stored)
    }
}

/// Local slot count only. Does not call a network, quota API, or sync.
pub fn cap_for(entitled: bool) -> usize {
    if entitled {
        PRO_CAP
    } else {
        FREE_CAP
    }
}

/// Drop (do not store) obvious secrets. Fail closed: the whole item is
/// rejected rather than redacted-and-kept, so confidential pasteboard
/// never lands on disk.
pub fn looks_like_secret(text: &str) -> bool {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return false;
    }
    if pem_private_key(trimmed) {
        return true;
    }
    if jwt_blob(trimmed) {
        return true;
    }
    if uri_with_embedded_password(trimmed) {
        return true;
    }
    if assignment_secret(trimmed) {
        return true;
    }
    token_prefix_secret(trimmed)
}

fn pem_private_key(text: &str) -> bool {
    text.contains("BEGIN PRIVATE KEY")
        || text.contains("BEGIN RSA PRIVATE KEY")
        || text.contains("BEGIN EC PRIVATE KEY")
        || text.contains("BEGIN OPENSSH PRIVATE KEY")
        || text.contains("BEGIN DSA PRIVATE KEY")
}

fn jwt_blob(text: &str) -> bool {
    let token = text.split_whitespace().next().unwrap_or("");
    if !token.starts_with("eyJ") {
        return false;
    }
    token.bytes().filter(|b| *b == b'.').count() == 2 && token.len() > 40
}

fn uri_with_embedded_password(text: &str) -> bool {
    for word in text.split_whitespace() {
        let Some(scheme_end) = word.find("://") else {
            continue;
        };
        let rest = &word[scheme_end + 3..];
        if let Some(at) = rest.find('@') {
            let creds = &rest[..at];
            if creds.contains(':') && creds.len() > 2 {
                return true;
            }
        }
    }
    false
}

fn assignment_secret(text: &str) -> bool {
    let lower = text.to_ascii_lowercase();
    const KEYS: &[&str] = &[
        "password",
        "passwd",
        "secret",
        "api_key",
        "apikey",
        "access_token",
        "auth_token",
        "authorization",
        "aws_secret_access_key",
        "private_key",
        "client_secret",
    ];
    for line in lower.lines() {
        let line = line.trim();
        for key in KEYS {
            for sep in [":", "=", " "] {
                let prefix = format!("{key}{sep}");
                if let Some(rest) = line.strip_prefix(&prefix) {
                    if !rest.trim().is_empty() {
                        return true;
                    }
                }
            }
        }
        if line.contains("bearer ") && line.split_whitespace().any(|w| w.len() > 12) {
            return true;
        }
    }
    false
}

fn token_prefix_secret(text: &str) -> bool {
    const PREFIXES: &[&str] = &[
        "gsk_",
        "sk_live_",
        "sk_test_",
        "rk_live_",
        "rk_test_",
        "ghp_",
        "github_pat_",
        "gho_",
        "ghs_",
        "ghu_",
        "xoxb-",
        "xoxp-",
        "xoxa-",
        "xoxs-",
        "xoxe-",
        "xoxc-",
        "AKIA",
        "AIza",
    ];
    for word in text.split_whitespace() {
        for prefix in PREFIXES {
            if word.starts_with(prefix) && word.len() > prefix.len() + 8 {
                return true;
            }
        }
    }
    false
}

pub fn should_skip_types(types: &[String]) -> bool {
    types.iter().any(|t| is_skip_uti(t))
}

pub fn is_skip_uti(uti: &str) -> bool {
    SKIP_UTIS
        .iter()
        .any(|known| known.eq_ignore_ascii_case(uti.trim()))
}

pub fn has_plain_text_type(types: &[String]) -> bool {
    types.iter().any(|t| {
        TEXT_UTIS
            .iter()
            .any(|known| known.eq_ignore_ascii_case(t.trim()))
    })
}

pub fn should_soft_skip_image(types: &[String]) -> bool {
    if has_plain_text_type(types) {
        return false;
    }
    types.iter().any(|t| {
        IMAGE_UTIS
            .iter()
            .any(|known| known.eq_ignore_ascii_case(t.trim()))
    })
}

fn item_view(item: &HistoryItem) -> HistoryItemView {
    HistoryItemView {
        id: item.id.clone(),
        preview: preview_text(&item.text),
        text_len: item.text.len(),
        created_at: item.created_at,
    }
}

pub fn preview_text(text: &str) -> String {
    let collapsed: String = text.split_whitespace().collect::<Vec<_>>().join(" ");
    const LIMIT: usize = 140;
    if collapsed.chars().count() <= LIMIT {
        collapsed
    } else {
        let mut out: String = collapsed.chars().take(LIMIT).collect();
        out.push('…');
        out
    }
}

fn apply_cap(items: &mut Vec<HistoryItem>, cap: usize) {
    if items.len() > cap {
        items.truncate(cap);
    }
}

fn load_file(app_dir: &PathBuf) -> Result<HistoryFile, String> {
    match crate::storage::read_existing_json::<HistoryFile>(
        &app_dir.join(HISTORY_FILE),
        "clipboard history",
    ) {
        Ok(Some(file)) => Ok(file),
        Ok(None) => Ok(HistoryFile::default()),
        Err(e) => Err(e),
    }
}

fn persist(app_dir: &PathBuf, file: &HistoryFile) -> Result<(), String> {
    fs::create_dir_all(app_dir).map_err(|e| e.to_string())?;
    let json = serde_json::to_string_pretty(file).map_err(|e| e.to_string())?;
    fs::write(app_dir.join(HISTORY_FILE), json).map_err(|e| e.to_string())
}

fn next_id() -> String {
    let n = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!("{n:x}")
}

fn now_secs() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    fn tmp() -> PathBuf {
        static N: AtomicU64 = AtomicU64::new(0);
        let dir = std::env::temp_dir().join(format!(
            "mabel-clip-{}-{}",
            std::process::id(),
            N.fetch_add(1, Ordering::Relaxed)
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn types(list: &[&str]) -> Vec<String> {
        list.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn default_off_fails_closed_and_does_not_store() {
        let dir = tmp();
        let svc = Service::new(dir.clone(), false);
        assert!(!svc.is_enabled());
        let decision = svc
            .capture_text("secret", &types(&["public.utf8-plain-text"]))
            .unwrap();
        assert_eq!(decision, CaptureDecision::Disabled);
        assert_eq!(svc.list().unwrap().count, 0);
        assert!(!dir.join(HISTORY_FILE).exists());
    }

    #[test]
    fn concealed_transient_autogenerated_and_password_utis_are_skipped() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        for uti in [
            "org.nspasteboard.ConcealedType",
            "ORG.NSPASTEBOARD.CONCEALEDTYPE",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
            "com.lastpass.sl",
            "de.petermaurer.TransientPasteboardType",
            "com.typeit4me.clipping",
            "Pasteboard generator type",
            "net.antelle.keeweb",
            "com.bitwarden.clipboard",
        ] {
            let decision = svc
                .capture_text("password", &types(&["public.utf8-plain-text", uti]))
                .unwrap();
            assert_eq!(
                decision,
                CaptureDecision::SkippedConfidential,
                "expected skip for {uti}"
            );
        }
        assert_eq!(svc.list().unwrap().count, 0);
    }

    #[test]
    fn image_only_soft_skips_without_storing() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        let decision = svc
            .capture_text("", &types(&["public.png", "public.tiff"]))
            .unwrap();
        assert_eq!(decision, CaptureDecision::SkippedImage);
        assert_eq!(svc.list().unwrap().count, 0);
    }

    #[test]
    fn text_plus_image_keeps_text() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        let decision = svc
            .capture_text(
                "hello",
                &types(&["public.utf8-plain-text", "public.png"]),
            )
            .unwrap();
        assert_eq!(decision, CaptureDecision::Stored);
        assert_eq!(svc.list().unwrap().count, 1);
    }

    #[test]
    fn free_cap_keeps_last_25() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        for i in 0..30 {
            svc.capture_text(&format!("item-{i}"), &types(&["public.utf8-plain-text"]))
                .unwrap();
        }
        let list = svc.list().unwrap();
        assert!(!list.entitled);
        assert_eq!(list.cap, FREE_CAP);
        assert_eq!(list.count, FREE_CAP);
        assert_eq!(list.items[0].preview, "item-29");
        assert_eq!(list.items[24].preview, "item-5");
    }

    #[test]
    fn pro_cap_constant_is_documented_sane_ceiling() {
        assert_eq!(PRO_CAP, 10_000);
        assert!(PRO_CAP > FREE_CAP);
        assert_eq!(cap_for(false), FREE_CAP);
        assert_eq!(cap_for(true), PRO_CAP);
    }

    #[test]
    fn opt_out_wipes_file() {
        let dir = tmp();
        let svc = Service::new(dir.clone(), true);
        svc.capture_text("keep me", &types(&["public.utf8-plain-text"]))
            .unwrap();
        assert!(dir.join(HISTORY_FILE).exists());
        svc.set_enabled(false).unwrap();
        assert!(!svc.is_enabled());
        assert!(!dir.join(HISTORY_FILE).exists());
        assert_eq!(svc.list().unwrap().count, 0);
    }

    #[test]
    fn consecutive_duplicate_is_not_stored_twice() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        let t = types(&["public.utf8-plain-text"]);
        assert_eq!(svc.capture_text("same", &t).unwrap(), CaptureDecision::Stored);
        assert_eq!(svc.capture_text("same", &t).unwrap(), CaptureDecision::Deduped);
        assert_eq!(svc.list().unwrap().count, 1);
    }

    #[test]
    fn huge_text_is_soft_skipped() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        let huge = "x".repeat(MAX_TEXT_BYTES + 1);
        let decision = svc
            .capture_text(&huge, &types(&["public.utf8-plain-text"]))
            .unwrap();
        assert_eq!(decision, CaptureDecision::SkippedHuge);
    }

    #[test]
    fn empty_or_whitespace_is_skipped() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        let t = types(&["public.utf8-plain-text"]);
        assert_eq!(
            svc.capture_text("   \n", &t).unwrap(),
            CaptureDecision::SkippedEmpty
        );
    }

    #[test]
    fn skip_list_covers_nspasteboard_org_conventions() {
        for required in [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
        ] {
            assert!(
                SKIP_UTIS.iter().any(|u| *u == required),
                "missing required skip UTI {required}"
            );
        }
        assert!(should_skip_types(&types(&["org.nspasteboard.ConcealedType"])));
        assert!(!should_skip_types(&types(&["public.utf8-plain-text"])));
    }

    #[test]
    fn preview_collapses_whitespace() {
        assert_eq!(preview_text("hello\n\n  world"), "hello world");
    }

    #[test]
    fn menu_bar_item_and_paste_reuse_are_wired() {
        let ui = include_str!("clipboard_ui.rs");
        assert!(ui.contains("Clipboard History…"));
        assert!(ui.contains("Polish"));
        let main = include_str!("main.rs");
        assert!(main.contains("mabel_lib::paste::paste_text"));
        assert!(main.contains("clipboard_history_paste"));
        assert!(!main.contains("MabelSpatial"));
    }

    #[test]
    fn version_and_storekit_train_stay_on_1_4_0() {
        let conf = include_str!("../tauri.conf.json");
        assert!(conf.contains("\"version\": \"1.4.0\""));
        let whats = include_str!("../../docs/whatsnew.md");
        assert!(whats.contains("## v1.4.0"));
        assert!(!whats.contains("## v1.5.0"));
    }

    #[test]
    fn no_os_permission_fails_closed() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        let decision = svc
            .capture_with_access(
                "hello from pasteboard",
                &types(&["public.utf8-plain-text"]),
                false,
            )
            .unwrap();
        assert_eq!(decision, CaptureDecision::DeniedPermission);
        assert_eq!(svc.list().unwrap().count, 0);
    }

    #[test]
    fn obvious_secrets_are_dropped_not_stored() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        let t = types(&["public.utf8-plain-text"]);
        // Assemble at runtime so the file never contains a scanner-shaped token.
        let secrets = [
            "-----BEGIN OPENSSH PRIVATE KEY-----\nfake\n-----END OPENSSH PRIVATE KEY-----"
                .to_string(),
            format!("{}{}", "gsk_", "abcdefghijklmnopqrstuvwxyz123456"),
            format!("{}{}{}", "sk_", "live_", "abcdefghijklmnopqrstuvwxyz"),
            format!("{}{}", "ghp_", "abcdefghijklmnopqrstuvwxyz1234"),
            format!("{}{}", "xoxb-", "1234567890-abcdefghijklmnop"),
            format!("{}{}", "AKIA", "AAAAAAAAAAAAAAAA"),
            format!("{}{}", "password=", "hunter2"),
            format!("{}{}", "api_key: ", "super-secret-value"),
            format!("{}{}", "postgres://user:", "s3cret@localhost:5432/db"),
            format!(
                "{}{}{}{}",
                "eyJ",
                "hbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
                ".eyJzdWIiOiIxMjM0In0.",
                "signaturepart"
            ),
        ];
        for secret in secrets {
            let decision = svc.capture_text(&secret, &t).unwrap();
            assert_eq!(
                decision,
                CaptureDecision::SkippedSecret,
                "should drop {secret}"
            );
        }
        assert_eq!(svc.list().unwrap().count, 0);
        assert!(!looks_like_secret("meeting notes for Thursday"));
    }

    #[test]
    fn wipe_is_local_file_delete_not_logged() {
        let src = include_str!("clipboard_history.rs");
        let prod = src.split("#[cfg(test)]").next().unwrap();
        assert!(prod.contains("fs::remove_file"));
        assert!(!prod.contains("reqwest::"));
        let wipe = prod.split("pub fn wipe").nth(1).unwrap();
        let wipe = wipe.split("pub fn list").next().unwrap();
        assert!(wipe.contains("remove_file"));
        assert!(!wipe.contains("reqwest"));
        assert!(!wipe.contains("Emitter"));
    }

    #[test]
    fn isolated_from_nexus_coach_and_cloud_quota() {
        let src = include_str!("clipboard_history.rs");
        assert!(src.contains("local slot counts"));
        assert!(src.contains("HISTORY_FILE"));
        let main = include_str!("main.rs");
        let clear = main.split("fn clipboard_history_clear").nth(1).unwrap();
        let clear = clear.split("fn clipboard_history_paste").next().unwrap();
        assert!(clear.contains("wipe"));
        assert!(!clear.contains("reqwest"));
        assert!(main.contains("clipboard_history_enabled"));
        assert!(!main.contains("nexusClipboard"));
        assert!(!main.contains("MabelSpatial"));
        assert!(src.contains("localSlotsOnly"));
    }

    #[test]
    fn list_marks_local_slots_only() {
        let dir = tmp();
        let svc = Service::new(dir, true);
        let list = svc.list().unwrap();
        assert!(list.local_slots_only);
        assert_eq!(list.cap, FREE_CAP);
    }

    #[test]
    fn setting_name_is_not_a_nexus_clipboard_toggle() {
        let settings = include_str!("settings.rs");
        assert!(settings.contains("clipboardHistoryEnabled"));
        assert!(!settings.contains("nexusClipboard"));
        assert!(settings.contains("must not"));
        assert!(settings.contains("poll or read pasteboard"));
    }

    #[test]
    fn corrupt_history_file_is_not_wiped() {
        let dir = tmp();
        fs::write(dir.join(HISTORY_FILE), "{nope").unwrap();
        let svc = Service::new(dir.clone(), true);
        let err = svc.list().unwrap_err();
        assert!(err.contains("left untouched"), "{err}");
        assert_eq!(fs::read_to_string(dir.join(HISTORY_FILE)).unwrap(), "{nope");
        assert!(svc.capture_text("x", &types(&["public.utf8-plain-text"])).is_err());
        assert_eq!(fs::read_to_string(dir.join(HISTORY_FILE)).unwrap(), "{nope");
    }
}
