//! NSPasteboard access for clipboard history and dictation inject marks.
//!
//! Types are inspected before any string payload is read. When history is
//! off, the poller must not call into this module at all.

#![cfg(target_os = "macos")]

use objc2::msg_send;
use objc2::runtime::AnyObject;
use std::ffi::{CStr, CString};
use std::os::raw::c_char;

use crate::clipboard_history;

const TRANSIENT: &str = "org.nspasteboard.TransientType";
const AUTO_GENERATED: &str = "org.nspasteboard.AutoGeneratedType";
const STRING_TYPE: &str = "public.utf8-plain-text";

struct AutoreleasePool {
    pool: *mut AnyObject,
}

impl AutoreleasePool {
    fn new() -> Self {
        unsafe {
            let cls = objc2::class!(NSAutoreleasePool);
            let pool: *mut AnyObject = msg_send![cls, new];
            Self { pool }
        }
    }
}

impl Drop for AutoreleasePool {
    fn drop(&mut self) {
        unsafe {
            if !self.pool.is_null() {
                let _: () = msg_send![self.pool, drain];
            }
        }
    }
}

fn nsstring(value: &str) -> *mut AnyObject {
    let c = CString::new(value).unwrap_or_else(|_| CString::new("").unwrap());
    unsafe {
        let cls = objc2::class!(NSString);
        msg_send![cls, stringWithUTF8String: c.as_ptr() as *const c_char]
    }
}

fn nsstring_to_rust(ns: *mut AnyObject) -> Option<String> {
    if ns.is_null() {
        return None;
    }
    unsafe {
        let utf8: *const c_char = msg_send![ns, UTF8String];
        if utf8.is_null() {
            return None;
        }
        Some(CStr::from_ptr(utf8).to_string_lossy().into_owned())
    }
}

fn general_pasteboard() -> *mut AnyObject {
    unsafe {
        let cls = objc2::class!(NSPasteboard);
        msg_send![cls, generalPasteboard]
    }
}

pub fn change_count() -> i64 {
    let _pool = AutoreleasePool::new();
    unsafe {
        let pb = general_pasteboard();
        if pb.is_null() {
            return 0;
        }
        let count: isize = msg_send![pb, changeCount];
        count as i64
    }
}

pub fn pasteboard_types() -> Vec<String> {
    let _pool = AutoreleasePool::new();
    unsafe {
        let pb = general_pasteboard();
        if pb.is_null() {
            return Vec::new();
        }
        let arr: *mut AnyObject = msg_send![pb, types];
        if arr.is_null() {
            return Vec::new();
        }
        let count: usize = msg_send![arr, count];
        let mut out = Vec::with_capacity(count);
        for i in 0..count {
            let item: *mut AnyObject = msg_send![arr, objectAtIndex: i];
            if let Some(s) = nsstring_to_rust(item) {
                out.push(s);
            }
        }
        out
    }
}

/// Read plain text only after `clipboard_history::should_skip_types` is false.
pub fn read_plain_text() -> Option<String> {
    let _pool = AutoreleasePool::new();
    unsafe {
        let pb = general_pasteboard();
        if pb.is_null() {
            return None;
        }
        let ty = nsstring(STRING_TYPE);
        let ns: *mut AnyObject = msg_send![pb, stringForType: ty];
        nsstring_to_rust(ns)
    }
}

/// Mark the current general-pasteboard contents as Transient + AutoGenerated
/// so clipboard history (ours and others that honor nspasteboard.org) does
/// not persist Mabel's dictation inject or restore write.
pub fn mark_mabel_pasteboard_write() {
    let _pool = AutoreleasePool::new();
    unsafe {
        let pb = general_pasteboard();
        if pb.is_null() {
            return;
        }
        let data_cls = objc2::class!(NSData);
        let empty: *mut AnyObject = msg_send![data_cls, data];
        if empty.is_null() {
            return;
        }
        for marker in [TRANSIENT, AUTO_GENERATED] {
            let ty = nsstring(marker);
            let _: bool = msg_send![pb, setData: empty, forType: ty];
        }
    }
}

pub fn pasteboard_accessible() -> bool {
    let _pool = AutoreleasePool::new();
    !general_pasteboard().is_null()
}

/// One poll tick. The caller must already have confirmed opt-in is on.
/// Types are inspected before any string payload is read. If the OS
/// pasteboard handle is unavailable, fail closed (no types, no string).
pub fn poll_capture(service: &clipboard_history::Service, last_change: &mut i64, primed: &mut bool) {
    if !pasteboard_accessible() {
        return;
    }
    let count = change_count();
    if !*primed {
        *last_change = count;
        *primed = true;
        return;
    }
    if count == *last_change {
        return;
    }
    *last_change = count;

    let types = pasteboard_types();
    if clipboard_history::should_skip_types(&types) {
        return;
    }
    if clipboard_history::should_soft_skip_image(&types) {
        return;
    }
    if !clipboard_history::has_plain_text_type(&types) && types.iter().any(|t| {
        t.eq_ignore_ascii_case("public.png")
            || t.eq_ignore_ascii_case("public.tiff")
            || t.eq_ignore_ascii_case("public.image")
    }) {
        return;
    }
    let Some(text) = read_plain_text() else {
        return;
    };
    let _ = service.capture_with_access(&text, &types, true);
}
